### ISSUE TITLE
licensing failure

### ISSUE THREAD

**Issue by zboldyga** [lassjs/lass#46]
Settings: version 1.0.11, node 10.x and 8.x, npm 5.6.0:

When selecting GPL-3.0 as the license during the 'lass new-package' process, I got this error:

`Initialized empty Git repository in /Users/hoopda/Documents/TerraClear/new-package/.git/
TypeError: console.log.error is not a function
    at post (/usr/local/lib/node_modules/lass/sao.js:168:21)
    at kopy.then.stream (/usr/local/lib/node_modules/lass/node_modules/sao/lib/generate.js:226:40)
    at <anonymous>`

Switching to MIT fixed the issue.

**Comment by niftylettuce** [comment]
will fix

**Comment by niftylettuce** [comment]
@zboldyga apologies, there was a breaking change with the package our CLI uses and v1.0.14 is non-working.  it has been fixed in 1.0.15.  sorry about that! `npm install -g lass@latest`
