### ISSUE TITLE
Error on package creation

### ISSUE THREAD

**Issue by sebacruz** [lassjs/lass#66]
I'm getting the following error creating a new package:

```
  test/test.js:1:14
  ✖   1:14  Do not use "require".  unicorn/prefer-module
  ✖   3:16  Do not use "require".  unicorn/prefer-module

  index.js:14:1
  ✖  14:1   Do not use "module".   unicorn/prefer-module

  3 errors
(node:86940) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: ./node_modules/.bin/xo --fix
    at makeError (/Users/sebas/.npm-global/lib/node_modules/lass/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/sebas/.npm-global/lib/node_modules/lass/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async post (/Users/sebas/.npm-global/lib/node_modules/lass/sao.js:222:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:86940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can you get me a hint on how to fix it?

**Comment by Spence-S** [comment]
as work around until the fix is published, in package.json under xo field you can add 

```json
"rules": {
  "unicorn/prefer-module": "off"
}
```
