### ISSUE TITLE
Error on first usage: Cannot read config file

### ISSUE THREAD

**Issue by vedmant** [lassjs/lass#67]
Hi, I have an error after trying to create a project with `lass new-package`:

```
Error: Cannot read config file: /Users/vedmant/Projects/_My/test/new-package/node_modules/eslint-config-prettier/standard.js
Error: "prettier/standard" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: BaseConfig
    at Object.<anonymous> (/Users/vedmant/Projects/_My/test/new-package/node_modules/eslint-config-prettier/standard.js:1:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at module.exports (/Users/vedmant/Projects/_My/test/new-package/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/vedmant/Projects/_My/test/new-package/node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
    at loadConfigFile (/Users/vedmant/Projects/_My/test/new-package/node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/Users/vedmant/Projects/_My/test/new-package/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
(node:6492) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: ./node_modules/.bin/xo --fix
    at makeError (/Users/vedmant/.config/yarn/global/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/vedmant/.config/yarn/global/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async post (/Users/vedmant/.config/yarn/global/node_modules/lass/sao.js:222:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by titanism** [comment]
v3.1.1 released
